name: CI

permissions:
  id-token: write # id-token is required to for OIDC

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-support:
    name: Lint and set up test-support
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - uses: aws-actions/configure-aws-credentials@be2e7ad815e27b890489a89ce2717b0f9e26b56e # v4
        with:
          role-to-assume: arn:aws:iam::459781239556:role/libmodal-ci-cd-role-62a288d
          aws-region: us-east-1

      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
        with:
          python-version: "3.13"

      - run: |
          uv python install

      - name: Build submodule client
        working-directory: modal-client
        env:
          VIRTUAL_ENV: .venv
        run: |
          uv venv
          uv pip install -r requirements.dev.txt
          uv pip install .
          uv pip install "synchronicity[compile]~=0.10.3"
          uv run inv protoc
          uv run inv type-stubs

      - name: Install submodule client
        run: uv pip install ./modal-client

      - run: |
          uv pip install ruff
          ruff check test-support/
          ruff format --check test-support/

      - run: test-support/setup.sh
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          MODAL_ENVIRONMENT: libmodal
          MODAL_SYNC_ENTRYPOINT: 1

  js:
    name: modal-js build, lint, and test
    runs-on: ubuntu-latest
    needs: test-support

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - uses: oven-sh/setup-bun@v2

      - run: bun install
        working-directory: ./modal-js

      - run: bun run format:check
        working-directory: ./modal-js

      - run: bun run check
        working-directory: ./modal-js

      - run: bun run lint
        working-directory: ./modal-js

      - run: bun run build
        working-directory: ./modal-js

      - run: bun test
        working-directory: ./modal-js
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          MODAL_ENVIRONMENT: libmodal

